### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by kimcyb** [libbitcoin/libbitcoin#1017]
I don't know solve this error
"libbitcoin::bitcoin_hash(libbitcoin::array_slice<unsigned char>)", referenced from:
      _main in gen_private_key-c4b82b.o
  "libbitcoin::encode_base16(libbitcoin::array_slice<unsigned char>)", referenced from:
      _main in gen_private_key-c4b82b.o
  "libbitcoin::pseudo_random_fill(std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >&)", referenced from:
      _main in gen_private_key-c4b82b.o
  "libbitcoin::config::checkpoint::checkpoint(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long)", referenced from:
      ___cxx_global_var_init in gen_private_key-c4b82b.o
      ___cxx_global_var_init.1 in gen_private_key-c4b82b.o
  "boost::system::system_category()", referenced from:
      boost::asio::error::get_system_category() in gen_private_key-c4b82b.o
  "boost::system::generic_category()", referenced from:
      boost::system::error_category::std_category::equivalent(int, std::__1::error_condition const&) const in gen_private_key-c4b82b.o
      boost::system::error_category::std_category::equivalent(std::__1::error_code const&, int) const in gen_private_key-c4b82b.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by thecodefactory** [comment]
@kimcyb Are you using the install.sh script for building?

**Comment by evoskuil** [comment]
Need to fix your boost dependency.

**Comment by thecodefactory** [comment]
This seems an odd mix of commands (apt-get and brew all at once), so some parts may have worked and some may have failed.  Try the following as a way to start cleanly:

```
wget https://raw.githubusercontent.com/libbitcoin/libbitcoin/version3/install.sh
chmod +x install.sh
./install.sh --prefix=/home/me/myprefix --build-boost --disable-shared
```

Where `/home/me/myprefix` is something like `$HOME/libbitcoin`.

When that's complete (and only if that completes properly), try:

```
PKG_CONFIG_PATH=$HOME/libbitcoin/lib/pkgconfig g++ -std=c++11 gen_private_key.cpp -o genPrivateKey $(pkg-config --cflags --libs libbitcoin)
```

**Comment by kimcyb** [comment]
I try and compile is ok
then
./genPrivateKey 
yet Error => Segmentation fault: 11

my code(gen_private_key.cpp) follows

#include <bitcoin/bitcoin.hpp>
#include <string.h>
#include <iostream>

using namespace bc;

int main(int argc, char const *argv[])
{
    /* code */
    data_chunk seed(16);
    pseudo_random_fill(seed);
    ec_secret secretKey = bitcoin_hash(seed);
    std::string hexKey = encode_base16(secretKey);
    std::cout << "Hex secret: " << std::endl;
    std::cout << hexKey << std::endl;
    return 0;
}

**Comment by thecodefactory** [comment]
Can you run this command (assuming OS X):

```
otool -L genPrivateKey
```

I suspect something is still broken about your build/install environment.

Also worth dumping some env vars:

```
env | grep DYLD
env | grep PKG
```

**Comment by thecodefactory** [comment]
Your compiled program is showing that it's using shared libraries installed in system directories.  This means that if you ran the install.sh using the options `--prefix=/home/me/myprefix --build-boost --disable-shared`, it's not what you compiled your program against.  Mismatching boost versions can cause crashes, which appears to be what's happening in your case.

Please make sure the install.sh succeeds with the instructions provided above, and use the PKG_CONFIG_PATH setting shown above before compiling your program to be sure.  If you run into an issue during those steps, show which error you're seeing.

**Comment by kimcyb** [comment]
I ran follows
PKG_CONFIG_PATH=$HOME/libbitcoin/lib/pkgconfig g++ -std=c++11 gen_private_key.cpp -o genPrivateKey $(pkg-config --cflags --libs libbitcoin)
then I got same error "Segmentation fault: 11" so
I ran otool -L genPrivateKey
but same printed above.
before build I ran
./install.sh --prefix=$HOME/libbitcoin --build-boost --disable-shared
then I got result
PASS: libbitcoin-test_runner.sh
============================================================================
Testsuite summary for libbitcoin 3.4.0
============================================================================
# TOTAL: 1
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
Running 1894 test cases...
Platform: Mac OS
Compiler: Clang version 9.1.0 (clang-902.0.39.2)
STL     : libc++ version 5000
Boost   : 1.57.0
but I don't know Why I ran genPrivateKey with pefix option but it compiled with wrong lib(usr/local..)

**Comment by kimcyb** [comment]
I solved belows
1. export PKG_CONFIG_PATH=$HOME/libbitcoin/lib/pkgconfig
2. PKG_CONFIG_PATH=$HOME/libbitcoin/lib/pkgconfig g++ -std=c++11 gen_private_key.cpp -o genPrivateKey $(pkg-config --cflags --libs libbitcoin)
then
I got error 
OSMemoryBarrier' is deprecated: first deprecated in macOS 10.12 - Use std::atomic_thread_fence() from <atomic>
      instead [-Wdeprecated-declarations]
    OSMemoryBarrier();
so I fixed refer https://github.com/chriskohlhoff/asio/pull/149/files/95f8b7ccc36c4bae0b33d9bf2400e9a150091498#diff-a55311c045edba6fffed9ec8fc76be48

**Comment by thecodefactory** [comment]
> Why I ran genPrivateKey with pefix option but it compiled with wrong lib(usr/local..)

Something is still not right in your environment.

Try this:
```
PKG_CONFIG_PATH=$HOME/libbitcoin/lib/pkgconfig $(pkg-config --cflags --libs libbitcoin)
```

Perhaps this isn't returning what's expected, so I'd like to see the output.

**Comment by thecodefactory** [comment]
Oops, I posted before I saw your reply, please ignore the above.  Exporting seems to be the correct option. You no longer need the leading PKG_CONFIG_PATH on the g++ line.

**Comment by thecodefactory** [comment]
@kimcyb If you can confirm that your issue is resolved, I'll close this issue.
